create table if not exists public.scanner_snapshots (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    ticker text not null,
    premarket_change_pct double precision not null,
    volume bigint not null,
    last_updated_at timestamptz not null,
    session text not null default 'premarket',
    applied_min_change_pct double precision not null,
    applied_min_volume bigint not null
);

create index if not exists scanner_snapshots_created_at_idx
    on public.scanner_snapshots (created_at desc);
